### ISSUE TITLE
[DPlayer] ロード時エラー

### ISSUE THREAD

**Issue by unyacat** [ci7lus/miraktest-plugins#13]
## 環境
試したMirakTestバージョン: `MirakTest-2.0.0-rc.1-win`
試したDPlayerバージョン: `2022062121`
Windows10 21H2で実行．

## 内容
プラグインロード時にエラー発生(動作に問題はないように見えるが一応)

エラー文
```
[Plugin] 繝ｭ繝ｼ繝峨＠縺ｾ縺励◆: miraktest-dplayer.plugin.js
webpack-internal:///13:169
const DPlayerWrapper = Object(external_React_in_globalThis_React_["memo"])(({ isPlaying, isSeekable, opacity, zoom, ng }) => {
                                                                          ^

TypeError: Object(...) is not a function
    at eval (webpack-internal:///13:169:75)
    at Module.<anonymous> (evalmachine.<anonymous>:907:3)
    at t (evalmachine.<anonymous>:258:17)
    at _default (evalmachine.<anonymous>:291:16)
    at evalmachine.<anonymous>:292:2
    at Script.runInContext (node:vm:139:12)
    at Object.runInContext (node:vm:289:6)
    at u (C:\Users\unyacat\Downloads\mirakbeta\MirakTest-2.0.0-nightly-win\resources\app.asar\dist\main.electron.js:1932:277228)
    at async FSWatcher.<anonymous> (C:\Users\unyacat\Downloads\mirakbeta\MirakTest-2.0.0-nightly-win\resources\app.asar\dist\main.electron.js:1932:278011) miraktest-dplayer.plugin.js
```

**Comment by ci7lus** [comment]
これはメインプロセスでのロード失敗なのでレンダラーでの挙動には影響がないんですが、見栄えは悪いので気が向いたら修正してみます
