### ISSUE TITLE
[rmcn]ホストに接続できない

### ISSUE THREAD

**Issue by kilinbox** [ci7lus/miraktest-plugins#16]
rmcnプラグインを使ってホストに接続できない事象が発生しましたのでご報告します。

MirakTestバージョン: 2.0.0-rc.1
rmcnバージョン: 2022073018
OS: macOS 12.5 ARM64
手順
1. MirakTest 2.0.0-rc.1 に rmcn プラグイン 2022073018 をインストール(インストールしているプラグインはrmcnだけ)
2. MirakTest 2.0.0-rc.1 を起動
3. ブラウザ Chrome 103 から http://mirakt-remo.surge.sh/ にアクセス
4. 入力フォームに localhost:10171 を入力 → 画面に何も変化がない

MirakTestのDevToolコンソールは次のとおりです。

```
pluginPaths: 
Array(1)
0: "/Users/user/Library/Application Support/MirakTest/plugins/miraktest-rmcn.plugin.js"
length: 1
[[Prototype]]: Array(0)
main.js:2 [Plugin] 取り込み中: miraktest-rmcn.plugin.js
main.js:2 [Plugin] 読込中: rmcn (io.github.ci7lus.miraktest-plugins.rmcn, 0.0.2)
main.js:2 [Plugin] セットアップ中: rmcn (io.github.ci7lus.miraktest-plugins.rmcn, 0.0.2)
main.js:2 表示サービスを変更します: null
main.js:2 VLC Args: 
Array(2)
0: "--avcodec-hw=none"
1: "--http-user-agent=MirakTest/2.0.0-rc.1"
length: 2
[[Prototype]]: Array(0)
main.js:2 TypeError: atoms.globalContentPlayerSelectedServiceFamily is not a function
    at component (Renderer.tsx?2e0a:99:1)
    at va (main.js:2:418357)
    at vs (main.js:2:475798)
    at yl (main.js:2:464749)
    at pl (main.js:2:464677)
    at dl (main.js:2:464540)
    at tl (main.js:2:461351)
    at el (main.js:2:459888)
    at _ (main.js:2:1441195)
    at MessagePort.T (main.js:2:1441727)
main.js:2 Uncaught TypeError: atoms.globalContentPlayerSelectedServiceFamily is not a function
    at component (Renderer.tsx?2e0a:99:1)
    at va (main.js:2:418357)
    at vs (main.js:2:475798)
    at yl (main.js:2:464749)
    at pl (main.js:2:464677)
    at dl (main.js:2:464540)
    at tl (main.js:2:461351)
    at el (main.js:2:459888)
    at _ (main.js:2:1441195)
    at MessagePort.T (main.js:2:1441727)
```

ChromeのDevToolコンソールは次のとおりです。

```
WebSocket connection to 'ws://localhost:10171/' failed: 
(anonymous) @ index.b28041db.js:65
```

いつもありがとうございます。

**Comment by kilinbox** [comment]
こちらのプラグインはv2.0.0-rc2以上の機能と書かれていましたね。
大変失礼しました。

**Comment by ci7lus** [comment]
必要な変更をデフォルトブランチに入れていた気がしてたんですが入ってなかったです、先程入れたので最新のnightly(<https://github.com/ci7lus/MirakTest/actions/runs/2768178923>)では動くと思います（aarch64のdmgは`x86_64-apple-darwin-as-aarch64-build-image`です）

**Comment by kilinbox** [comment]
ご対応ありがとうございます。
nightlyで確認しました。
http://mirakt-remo.surge.sh/ にアクセスして
選択しているチャンネルの情報、チャンネルボタンが表示されたのですが、
「再生」と「SSを撮る」ボタン以下がグレーアウト状態でした。

MirakTestのDevToolコンソールは次のとおりです。

```
pluginPaths: Array(1)
main.js:2 [Plugin] 取り込み中: miraktest-rmcn.plugin.js
main.js:2 [Plugin] 読込中: rmcn (io.github.ci7lus.miraktest-plugins.rmcn, 0.0.2)
main.js:2 [Plugin] セットアップ中: rmcn (io.github.ci7lus.miraktest-plugins.rmcn, 0.0.2)
main.js:2 表示サービスを変更します: null
main.js:2 VLC Args: Array(2)0: "--avcodec-hw=none"1: "--http-user-agent=MirakTest/2.0.0-nightly+19eea3f"length: 2[[Prototype]]: Array(0)
main.js:2 画面サイズ変更: Array(2)0: 19201: 1080length: 2[[Prototype]]: Array(0)
index.html#ContentPlayer:1 Uncaught (in promise) Error: Error invoking remote method 'io.github.ci7lus.miraktest-plugins.rmcn.setServices': TypeError: Cannot read properties of null (reading 'forEach')
```

<img width="955" alt="スクリーンショット 2022-07-31 15 29 32" src="https://user-images.githubusercontent.com/17141779/182013263-f85b3055-8827-4662-aa92-aedfe80145fe.png">

**Comment by ci7lus** [comment]
見た目と実際に選択できるプレイヤーに食い違いが出るようだったので http://mirakt-remo.surge.sh/ 側に修正を加えました。今度こそ動くと思います（多分…

**Comment by kilinbox** [comment]
ばっちり動きました。
Macやスマホからリモコンが使えることを確認しました。
ありがとうございました。
